version: "3"
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: tvMv2gjAcH5a
    ports:
      - "3306:3306"
    networks:
      - offline
    volumes:
      - mysql-datavolume:/var/lib/mysql
  webhttps:
    image: leoschsenna/redcoins-sv:https
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
    ports:
      - "443:443"
    networks:
      - webnet
      - offline
  webhttp:
    image: leoschsenna/redcoins-sv:http
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
    ports:
      - "80:80"
    networks:
      - webnet
      - offline
networks:
  webnet:
  offline:
    internal: true
volumes:
  mysql-datavolume: